version: "2"
services:
  backend:
    container_name: appunta-backend
    image: mijara/appunta-backend
    restart: on-failure
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py loaddata final && gunicorn backend.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./media:/src/media
      - ./staticroot:/src/staticroot
    environment:
      - DJANGO_DEBUG=False
    ports:
      - "8000:8000"
  api:
    container_name: nginx
    image: nginx
    volumes:
      - ./media:/media
      - ./staticroot:/static
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "7000:7000"
    depends_on:
      - backend
  frontend:
    container_name: appunta-frontend
    image: mijara/appunta-frontend
    ports:
      - "8080:80"
    links:
      - api

